
import './globals.css'
import { Inter } from 'next/font/google'
import { dark } from '@mui/material/styles/createPalette'
import Footer from './sections/home/footer'
import MuiThemeProvider from './theme/MuiThemeProvider'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">    
      <body className={inter.className}>
      
      <MuiThemeProvider>  
        
        {children}
        <Footer/> 
      
      </MuiThemeProvider>
      
      </body>
    </html>
  )
}
